envision/models/post.py
from __future__ import unicode_literals, absolute_import, print_function

from uuid import uuid4
from datetime import datetime

from flask import url_for
from enum import Enum
from sqlalchemy.orm.exc import NoResultFound
from sqlalchemy_utils import UUIDType, ChoiceType
from misaka import html as render_markdown
from html5lib import HTMLParser, serialize
from html5lib.sanitizer import HTMLSanitizer
from html5lib_truncation import truncate_html

from envision.ext import db
from envision.models.user import User


def render_sanitized_html(html):
    parser = HTMLParser(tokenizer=HTMLSanitizer)
    etree = parser.parse(html)
    return serialize(etree)


class Post(db.Model):
    """The posts or articles."""

    class Status(Enum):
        publish = 'P'
        draft = 'D'
        trash = 'T'

    class ContentType(Enum):
        raw_html = 0
        markdown = 1

    ContentType.raw_html.as_html = render_sanitized_html
    ContentType.markdown.as_html = render_markdown

    uuid = db.Column(UUIDType(), primary_key=True, default=uuid4)
    title = db.Column(db.Unicode(30), nullable=False)
    slug = db.Column(db.Unicode(60), nullable=False, unique=True)
    author_id = db.Column(db.Integer(), nullable=False)
    author = db.relationship(
        User, uselist=False, primaryjoin='User.id == Post.author_id',
        foreign_keys='Post.author_id')
    status = db.Column(ChoiceType(Status), default=Status.draft)
    content = db.Column(db.Unicode(512))
    content_type = db.Column(
        ChoiceType(ContentType, impl=db.Integer()),
        default=ContentType.markdown)
    updated_at = db.Column(db.DateTime(), default=datetime.utcnow)
    created_at = db.Column(db.DateTime(), default=datetime.utcnow)

    @classmethod
    def create(cls, title, slug, author, status=None):
        instance = cls(title=title, slug=slug, author=author)
        if status is not None:
            instance.status = status
        return instance

    @classmethod
    def get_by_slug(cls, slug, status=None):
        try:
            instance = cls.query.filter_by(slug=slug).one()
        except NoResultFound:
            return
        else:
            if status not in (None, instance.status):
                return
            return instance

    @classmethod
    def get_latest_multi(cls, limit=10, status=Status.publish):
        query = cls.query.filter_by(status=status)
        return query.order_by(cls.created_at.desc())[:limit]

    @property
    def permalink(self):
        return url_for('index.post', slug=self.slug)

    def set_content(self, content, content_type=None):
        self.content = content
        if content_type:
            self.content_type = content_type

    def as_html(self, max_length=None, ellipsis=''):
        html = self.content_type.as_html(self.content)
        if max_length is not None:
            html = truncate_html(
                html, max_length, end=ellipsis, break_words=True)
        return html

envision/models/user.py
from __future__ import unicode_literals, absolute_import, print_function

from datetime import datetime

from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy.orm.exc import NoResultFound

from envision.ext import db


class User(UserMixin, db.Model):
    """The site users."""

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.Unicode(20), nullable=False, unique=True)
    password = db.Column(db.String(70), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    @classmethod
    def create(cls, email, password, is_active=False):
        instance = cls(email=email, is_active=is_active)
        instance.change_password(password)
        db.session.add(instance)
        return instance

    @classmethod
    def get_by_email(cls, email):
        try:
            return cls.query.filter_by(email=email).one()
        except NoResultFound:
            return

    def change_password(self, password):
        self.password = generate_password_hash(password)

    def verify_password(self, input_password):
        return check_password_hash(self.password, input_password)

envision/app.py
from __future__ import unicode_literals, absolute_import, print_function

from flask import Flask
from werkzeug.utils import import_string


extensions = [
    'envision.ext:db',
    'envision.ext:login_manager',
]
blueprints = [
    'envision.views.index:bp',
    'envision.views.user:bp',
]


def create_app():
    app = Flask(__name__)
    app.config.from_object('envcfg.json.envision')

    for extension_name in extensions:
        extension = import_string(extension_name)
        extension.init_app(app)

    for blueprint_name in blueprints:
        blueprint = import_string(blueprint_name)
        app.register_blueprint(blueprint)

    return app

envision/views/index.py
from __future__ import unicode_literals, absolute_import, print_function

from flask import Blueprint, render_template, abort

from envision.models.post import Post


bp = Blueprint('index', __name__)


@bp.route('/')
def index():
    posts = Post.get_latest_multi()
    return render_template('index.html', posts=posts)


@bp.route('/post/<slug>')
def post(slug):
    post = Post.get_by_slug(slug) or abort(404)
    return render_template('post.html', post=post)

envision/views/user.py
from __future__ import unicode_literals, absolute_import, print_function

from flask import Blueprint, render_template, request, flash, url_for, redirect
from flask_login import login_user, logout_user
from flask_wtf import Form
from wtforms import fields, validators

from envision.ext import login_manager
from envision.models.user import User


bp = Blueprint('user', __name__)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    next_url = request.args.get('next', default=url_for('index.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.get_by_email(form.data['email'])
        if user and user.verify_password(form.data['password']):
            login_user(user)
            flash('Logged in successfully.')
            return redirect(next_url)
        else:
            flash('The user does not exist or the password is wrong.')
    return render_template('login.html', form=form)


@bp.route('/logout', methods=['POST'])
def logout():
    logout_user()
    if request.is_xhr:
        return '', 204
    return redirect(url_for('user.login'))


class LoginForm(Form):
    email = fields.TextField('Email', validators=[
        validators.DataRequired(),
        validators.Email(),
    ])
    password = fields.PasswordField('Password', validators=[
        validators.DataRequired(),
    ])
    submit = fields.SubmitField('Login')

envision/templates/index.html
{% extends "layout/base.html" %}

{% block content %}
  {% for post in posts %}
  <div class="blog-content">
    <div class="blog-content-date">
      {{ post.created_at.strftime('%Y-%m-%d %H:%S') }}
    </div>
    <div class="blog-content-title">
      {{ post.title }}
    </div>
    <div class="blog-content-detial">
      {{ post.as_html(max_length=140, ellipsis='…') | safe }}
      <a href="{{ post.permalink }}">[更多]</a>
    </div>
  </div>

  <div class="blog-share">
    <ul class="blog-share-detail">
      <li><i class="fa fa-heart fa-lg"></i>621 LIKES</li>
      <li><i class="fa fa-share-alt fa-lg"></i>SHARE</li>
    </ul>
  </div>
  {% endfor %}
{% endblock %}

envision/templates/layout/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My Blog</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>
  <body>
    <div class="blog">
      <nav class="nav-title">
        <ul class="nav-title-bar">
          <li><a href="{{ url_for('index.index') }}">HOME</a></li>
          <li><a href="#">ARICHIVES</a></li>
          <li><a href="#">ABOUT ME</a></li>
          <li>{# TODO BEGINNING (CC @lttxzmj) #}
          {% if current_user.is_anonymous() %}
          <a href="{{ url_for('user.login') }}">LOG IN</a>
          {% else %}
          {{ current_user.email }}
          <form action="{{ url_for('user.logout') }}" method="post">
            <input type="submit" value="Logout">
          </form>
          {% endif %}
          {# TODO END (CC @lttxzmj) #}</li>
        </ul>
      </nav>


      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

envision/templates/login.html
{% extends "layout/base.html" %}

{% block content %}
{% with messages = get_flashed_messages() %}
  {% if messages %}
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  <hr>
  {% endif %}
{% endwith %}
<div class="content">
  <form class="main-form" action="{{ url_for('user.login') }}" method="post">
    {{ form.csrf_token() }}
    <div class="content-email">
      {{ form.email.label(class="label-email") }}
      {{ form.email(class="form-email") }}
    </div>
    <div class="content-password">
      {{ form.password.label(class="label-password") }}
      {{ form.password(class="form-password") }}
    </div>
    {{ form.submit(class="label-login") }}
    {% if form.errors %}
    <ul class="error">
      {% for name, errors in form.errors.items() %}
      <li>{{ name }}: {{ errors | join(', ') }}</li>
      {% endfor %}
    </ul>
    {% endif %}
  </form>
</div>
{% endblock %}

envision/templates/post.html
{% extends "layout/base.html" %}
{% block content %}
<div class="content">
  <div class="content-container ">
    <h2 class="content-title blog-content-title">{{ post.title }}</h2>
    <p class="content-detail">
      作者: {{ post.author.email }} <br>
      更新: {{ post.updated_at.strftime('%Y-%m-%d %H:%S') }} <br>
      创建: {{ post.created_at.strftime('%Y-%m-%d %H:%S') }} <br>
    </p>
  </div>
  <article class="content-article blog-content-detial">
  {{ post.as_html() | safe }}
  </article>
  <a href="{{ url_for('index.index') }}">[首页]</a>
</div>
{% endblock %}